services:
  - type: web
    name: securecity-iq
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python Securecity_IQ.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
